"use client";

import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import { Footer } from "@/components/footer";
import { SiteHeader } from "@/components/site-header";
import { CharacterReveal, Reveal, RevealImage, Stagger } from "@/components/motion";

const vision = "Our vision is to provide our consumers with seafood that is both healthy and ethical. The foundation of our business is relationship building, not just with our team but also with our clients and suppliers. Additionally, we believe it is critical for our business to support socially responsible and sustainable initiatives. This strategy guarantees good environmental and natural management.";
const visionContinued = "In order to do this, we only advertise fish and fish products that have been caught or raised in a sustainable manner, as well as those that have been processed, packaged, stored, and distributed with the highest care and in completely hygienic conditions.";
const mission = "Our mission is to grow into a sustainable aquaculture and food products, ensuring supply sufficiency, high quality of farming and production operations, affordability of logistical distribution and protection of the environment and natural resources.";
const history = "Pristine Fish Farm, a sole proprietorship LLC, was established in February 2021 and is owned by Al Jaraf Fisheries Group, one of the largest and most technically advanced producers of premium caviar from sustainably derived sources in the world.";
const historyContinued = "Pristine Caviar is the first caviar farm of its kind in Middle east and the largest controlled fish breeding and cultivation (pisciculture) RAS facility in the world.";
const historyFinal = "With its state of art facility in Abu Dhabi, Pristine caviar will produce and supply high quality sustainably sourced Caviar round the year to help satisfy around 10% of the gap in global demand of this gourmet food without endangering wild sturgeon stocks.";
const consulting = "Pristine is a UAE based aquaculture consulting company that provides aqua project management services worldwide. We are in the significant opportunities for water and wastewater treatment contracts within our Aqua division, as well as products and systems for land-based farming, industry and fisheries.";
const ceoMessage = "The nation would be qualified to compete in the international market with other nations. Regarding size and technology, this caviar factory is the largest in the world. Our goal is to become the largest caviar supplier in the world. Our skilled and committed team of professionals work around the clock to ensure the health and wellbeing of our farm and its many inhabitants. We offer our consumers high-quality, transparent, sustainable fish products based a good, reliable, and mutual relationships.”";

function Story({ eyebrow, title, copy, image, reverse = false, id }: { eyebrow: string; title: string; copy: React.ReactNode; image: string; reverse?: boolean; id?: string }) {
  return <section className={`editorial-story${reverse ? " editorial-story-reverse" : ""}`} id={id}><div className="editorial-shell editorial-story-grid"><Stagger className="editorial-story-copy about-story-copy"><Reveal><p className="eyebrow">{eyebrow}</p></Reveal><Reveal delay={.08}><h2><CharacterReveal text={title} /></h2></Reveal><Reveal delay={.16}><div>{copy}</div></Reveal></Stagger><RevealImage><div className="editorial-story-image"><Image src={image} alt="" fill sizes="(max-width: 760px) 100vw, 50vw" /></div></RevealImage></div></section>;
}

export function AboutPage() {
  return <><SiteHeader /><main><section className="editorial-hero inner-editorial-hero"><Image src="/images/farm-intro.jpg" alt="" fill priority sizes="100vw" /><div className="editorial-hero-shade" /><Stagger className="editorial-shell editorial-hero-copy" immediate><Reveal><p className="eyebrow">About Pristine</p></Reveal><Reveal delay={.1}><h1><CharacterReveal text="From Abu Dhabi, with control from farm to tin." /></h1></Reveal><Reveal delay={.2}><p>Pristine brings together controlled aquaculture, thoughtful handling and a considered caviar collection.</p></Reveal><Reveal delay={.3}><a className="button" href="#vision">Discover our approach <ArrowUpRight size={14} /></a></Reveal></Stagger></section><Story id="vision" eyebrow="Vision" title="VISION" copy={<><p>{vision}</p><p>{visionContinued}</p></>} image="/images/farm-infrastructure-environment.jpg" /><Story eyebrow="Mission" title="MISSION" copy={<p>{mission}</p>} image="/images/sturgeon-water.webp" reverse /><section className="editorial-section" id="history"><div className="editorial-shell editorial-story-copy about-story-copy"><Reveal><p className="eyebrow">History</p></Reveal><Reveal delay={.08}><h2><CharacterReveal text="HISTORY" /></h2></Reveal><Reveal delay={.16}><div><p>{history}</p><p>{historyContinued}</p><p>{historyFinal}</p></div></Reveal></div></section><Story eyebrow="Aquaculture consulting" title="AQUACULTURE CONSULTING" copy={<p>{consulting}</p>} image="/images/farm-infrastructure-systems.jpg" /><Story eyebrow="Leadership" title="CEO — MESSAGE" copy={<p>{ceoMessage}</p>} image="/images/dr-gopakumar.png" reverse /></main><Footer /></>;
}
