"use client";

import Image from "next/image";
import { ArrowUpRight, Check, Droplets, Fish, Leaf, Settings, ShieldCheck, Waves } from "lucide-react";
import { Footer } from "@/components/footer";
import { SiteHeader } from "@/components/site-header";
import { EnquirySection } from "@/components/migrated-content-sections";
import { PristineFarmSection } from "@/components/pristine-farm-section";
import { Reveal, RevealImage, Stagger } from "@/components/motion";

const whatsapp = "971545775900";
const caviar = [
  ["Sevruga Royal", "Delicate, refined and briny.", "/images/caviar-labels/sevruga-royal.webp"],
  ["Baerii Classic", "Mild, creamy and approachable.", "/images/caviar-labels/baerii-classic.webp"],
  ["Baerii Royal", "Silky, rich and versatile.", "/images/caviar-labels/baerii-royal.webp"],
  ["Osetra Royal", "Rich, nutty and bold.", "/images/caviar-labels/osetra-royal.webp"],
  ["Albino Royal", "Rare, delicate and buttery.", "/images/caviar-labels/albino-royal.webp"],
] as const;
const services = [["Feasibility Studies", "Early-stage assessment to help evaluate project practicality and direction.", Settings], ["Farm Planning", "Planning support for layout, scale and operating needs.", Leaf], ["RAS Design", "Recirculating aquaculture system planning for the intended production model.", Waves], ["Operational Management", "Support for day-to-day farm operations, systems and production discipline.", Fish], ["Biosecurity", "Practical planning to reduce biological risk and protect stock health.", ShieldCheck], ["Production Optimization", "Review and improvement of operating performance and consistency.", Droplets]] as const;
const certifications = [["ISO 22000:2018", "Food safety management"], ["HACCP", "Food safety controls"], ["BAP", "Best Aquaculture Practices"], ["Organic System", "Certified production system"], ["HALAL", "Certified"], ["CITES", "Sturgeon trade documentation"], ["MOCCA", "Licensed"], ["FDA Certified – USA", "USA market requirement"]] as const;

function Shell({ children }: { children: React.ReactNode }) { return <><SiteHeader /><main>{children}</main><Footer /></>; }
function Hero({ eyebrow, title, copy, image, action = "Make an enquiry", href = "/contact" }: { eyebrow: string; title: string; copy: string; image: string; action?: string; href?: string }) { return <section className="editorial-hero"><Image src={image} alt="" fill priority sizes="100vw" /><div className="editorial-hero-shade" /><Stagger className="editorial-shell editorial-hero-copy" immediate><Reveal><p className="eyebrow">{eyebrow}</p></Reveal><Reveal delay={.1}><h1>{title}</h1></Reveal><Reveal delay={.2}><p>{copy}</p></Reveal><Reveal delay={.3}><a className="button" href={href}>{action}<ArrowUpRight size={14} /></a></Reveal></Stagger></section>; }
function SplitStory({ eyebrow, title, copy, image, reverse = false }: { eyebrow: string; title: string; copy: string; image: string; reverse?: boolean }) { return <section className={`editorial-story${reverse ? " editorial-story-reverse" : ""}`}><div className="editorial-shell editorial-story-grid"><Stagger className="editorial-story-copy"><Reveal><p className="eyebrow">{eyebrow}</p></Reveal><Reveal delay={.08}><h2>{title}</h2></Reveal><Reveal delay={.16}><p>{copy}</p></Reveal></Stagger><RevealImage><div className="editorial-story-image"><Image src={image} alt="" fill sizes="(max-width: 760px) 100vw, 50vw" /></div></RevealImage></div></section>; }
function WhatsApp({ product }: { product: string }) { return <a className="content-link" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Hello Pristine Caviar, I am interested in ${product}. Please share suitable formats and a quotation.`)}`} target="_blank" rel="noreferrer">Enquire about this selection <ArrowUpRight size={14} /></a>; }

export function FarmPage() { return <Shell><Hero eyebrow="Our Farm · UAE" title="The farm is part of the luxury." copy="Pristine’s UAE aquaculture operation is shaped by controlled farming environments, traceability and careful handling." image="/images/farm-intro.jpg" action="Explore our farm" href="#farm-story" /><div id="farm-story"><PristineFarmSection /></div><SplitStory eyebrow="Controlled indoor farming" title="A considered environment for every stage." copy="Our farm is designed around thoughtful systems, daily observation and the careful conditions that support our sturgeon." image="/images/farm-infrastructure-environment.jpg" /><EnquirySection /></Shell>; }

export function CaviarPage() { return <Shell><Hero eyebrow="The Pristine Collection" title="Caviar, crafted in Abu Dhabi." copy="A considered collection of UAE-produced premium caviar, selected for individual character, texture and flavour." image="/images/caviar-editorial.webp" action="Explore the collection" href="#collection" /><section className="editorial-section editorial-collection" id="collection"><div className="editorial-shell"><Reveal><p className="eyebrow">Caviar selections</p><h2>Five expressions.<br />One Pristine standard.</h2></Reveal><Stagger className="editorial-product-grid">{caviar.map(([name, character, image]) => <Reveal key={name} variant={undefined}><article><Image src={image} alt={`${name} caviar label`} width={190} height={190} /><h3>{name}</h3><p>{character}</p><WhatsApp product={name} /></article></Reveal>)}</Stagger></div></section><SplitStory eyebrow="From farm to tin" title="A collection made for considered occasions." copy="Every selection begins with careful farming and ends with a direct conversation about the format best suited to your table or business." image="/images/farm-care-inspection.jpg" /><EnquirySection /></Shell>; }

export function AquaculturePage() { return <Shell><Hero eyebrow="Aquaculture Consultancy" title="From concept to optimized production." copy="Pristine provides aquaculture expertise and project support from early planning through operational requirements." image="/images/farm-infrastructure-systems.jpg" action="Start an aquaculture project" href="#services" /><section className="editorial-section editorial-dark" id="services"><div className="editorial-shell"><p className="eyebrow">Services</p><h2>Practical expertise for every phase.</h2><div className="editorial-service-grid">{services.map(([name, copy, Icon]) => <article key={name}><Icon /><h3>{name}</h3><p>{copy}</p></article>)}</div></div></section><section className="editorial-section"><div className="editorial-shell"><p className="eyebrow">Our process</p><h2>A clear route from first brief to ongoing support.</h2><ol className="editorial-process">{["Assess", "Plan", "Design", "Implement", "Optimize"].map((step, index) => <li key={step}><span>0{index + 1}</span><strong>{step}</strong></li>)}</ol></div></section><EnquirySection /></Shell>; }

export function SustainabilityPage() { return <Shell><Hero eyebrow="Responsible Aquaculture" title="Better farming through control, care and responsibility." copy="Pristine’s approach brings water management, traceability and careful farming together from source to selection." image="/images/sturgeon-water.webp" action="Learn more about our farm" href="/farm" /><SplitStory eyebrow="Controlled production" title="Responsibility begins with the environment we create." copy="A controlled farming setting helps our team observe conditions, care for stock and make considered decisions at every stage." image="/images/farm-care-hands-on.jpg" /><SplitStory eyebrow="Water & traceability" title="Quality from farm to tin." copy="Thoughtful water management, purposeful resource use and clear handling practices guide the journey from farm to final selection." image="/images/hero-landscape.webp" reverse /><section className="editorial-section editorial-statement"><div className="editorial-shell"><p className="eyebrow">Our approach</p><h2>Care for the fish, the water and the details that connect them.</h2><a className="button" href="/farm">Learn more about our farm <ArrowUpRight size={14} /></a></div></section></Shell>; }

export function QualityPage() { return <Shell><Hero eyebrow="Quality & Certifications" title="Standards customers can see and trust." copy="Pristine’s quality approach brings food safety, aquaculture standards, traceability and quality control into one considered process." image="/images/farm-care-inspection.jpg" action="Make an enquiry" href="/contact" /><section className="quality-section editorial-quality-page"><div className="container"><p className="eyebrow">Certification & verification</p><div className="content-heading"><h2>Quality at every<br />stage.</h2><p>Certification and registration claims below are shown from the approved reference source and require client verification before final publication.</p></div><div className="certification-grid">{certifications.map(([title, copy]) => <article key={title}><Check size={17} /><strong>{title}</strong><span>{copy}</span></article>)}</div></div></section><SplitStory eyebrow="Traceability & control" title="A measured approach from source to selection." copy="Food safety, product traceability and careful quality control inform how each selection is handled and presented." image="/images/caviar-editorial.webp" /><EnquirySection /></Shell>; }

export function ContactPage() { return <Shell><Hero eyebrow="Direct Enquiry" title="Tell us what you’re looking for." copy="Whether you are sourcing caviar, sturgeon or aquaculture support, begin a direct conversation with Pristine." image="/images/hero-landscape.webp" action="Start your enquiry" href="#enquire" /><section className="editorial-section editorial-contact"><div className="editorial-shell"><p className="eyebrow">Contact Pristine</p><div className="editorial-contact-grid"><h2>In Abu Dhabi and ready to help.</h2><div><p><a href="https://wa.me/971545775900" target="_blank" rel="noreferrer">WhatsApp: +971 54 577 5900</a><br /><a href="tel:+97125583621">+971 2 558 3621</a><br /><a href="mailto:nesrine@pristinecaviarfarm.com">nesrine@pristinecaviarfarm.com</a></p><p>Mussafah,<br />Abu Dhabi, UAE</p><p><a href="https://www.instagram.com/pristine_caviar/" target="_blank" rel="noreferrer">Instagram ↗</a><br /><a href="https://www.linkedin.com/company/pristine-caviar" target="_blank" rel="noreferrer">LinkedIn ↗</a></p></div></div></div></section><EnquirySection /></Shell>; }
