"use client";

import { FormEvent, useState } from "react";
import Image from "next/image";
import { ArrowUpRight, Check, Fish, Leaf, Settings, ShieldCheck, ShoppingBag, Waves } from "lucide-react";
import { CharacterReveal, Reveal, Stagger, collectionCardReveal, editorialCopyReveal } from "@/components/motion";

const whatsapp = "971545775900";
const varieties = [["Sevruga Royal", "Delicate · Refined · Briny", "/images/caviar-labels/sevruga-royal.webp"], ["Baerii Classic", "Mild · Creamy · Approachable", "/images/caviar-labels/baerii-classic.webp"], ["Baerii Royal", "Silky · Rich · Versatile", "/images/caviar-labels/baerii-royal.webp"], ["Osetra Royal", "Rich · Nutty · Bold", "/images/caviar-labels/osetra-royal.webp"], ["Albino Royal", "Rare · Delicate · Buttery", "/images/caviar-labels/albino-royal.webp"]] as const;
const audiences = [["Trade & Distribution", "For traders, wholesalers, importers and distributors requiring reliable caviar and sturgeon supply."], ["HoReCa & Events", "For hotels, restaurants, caterers, chefs, event companies and hospitality groups."], ["Retail & Supermarkets", "For supermarket chains and premium retail partners looking for retail-ready formats."], ["Private Customers", "For customers ordering directly for dining, celebrations, gifting and personal occasions."]] as const;
const sturgeon = [["Fresh Sturgeon Fillet", "Fresh, clean flavour with a firm, delicate texture."], ["Frozen Sturgeon Fillet", "Prepared for convenient cold storage and supply planning."], ["Smoked Sturgeon Fillet", "Rich, aromatic profile suited to buffets, canapés and gourmet platters."], ["Whole Sturgeon", "For larger hospitality, event and specialist preparation requirements."]] as const;
const consultancy = [["Feasibility Studies", "Early-stage assessment to help evaluate project practicality and direction.", Settings], ["Farm Planning", "Planning support for aquaculture farm layout, scale and operating needs.", Leaf], ["RAS Design", "Recirculating aquaculture system planning suited to the intended production model.", Waves], ["Operational Management", "Support for day-to-day farm operation, systems and production discipline.", Fish], ["Biosecurity", "Practical planning to reduce biological risk and protect stock health.", ShieldCheck], ["Production Optimization", "Review and improvement of operating performance, consistency and output.", ShoppingBag]] as const;
const certifications = [["ISO 22000:2018", "Food safety management"], ["HACCP", "Food safety controls"], ["BAP", "Best Aquaculture Practices"], ["Organic System", "Certified production system"], ["HALAL", "Certified"], ["CITES", "Sturgeon trade documentation"], ["MOCCA", "Licensed"], ["FDA Certified – USA", "USA market requirement"]] as const;

function WhatsAppLink({ children, message, className = "content-link" }: { children: React.ReactNode; message: string; className?: string }) { return <a className={className} href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14} /></a>; }

export function ProductAndAudienceSections() { return <><section className="content-section collection" id="caviar"><div className="container"><p className="eyebrow">The Pristine Collection</p><div className="content-heading collection-heading"><h2><CharacterReveal text="Five expressions. One Pristine standard." /></h2><Reveal variant={editorialCopyReveal} delay={0.3}><p>Explore the five core caviar varieties. Pricing is handled by enquiry, so every customer receives the right format, quantity and commercial offer.</p></Reveal></div><Stagger className="collection-grid">{varieties.map(([name, character, image]) => <Reveal key={name} className="collection-card-reveal" variant={collectionCardReveal}><article><span>Pristine Caviar</span><Image className="collection-label" src={image} alt={`${name} caviar label`} width={180} height={180} /><h3>{name}</h3><p>{character}</p><WhatsAppLink message={`Hello Pristine Caviar, I am interested in ${name}. Please share suitable formats and a quotation.`}>Enquire about this caviar</WhatsAppLink></article></Reveal>)}</Stagger></div></section><section className="content-section audience-section" id="audiences"><div className="container"><p className="eyebrow">Who we serve</p><div className="content-heading"><h2>One brand.<br />Four buying journeys.</h2><p>Customers do not need to navigate the same buying process. Select the route designed for your audience.</p></div><div className="audience-grid">{audiences.map(([name, description], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{description}</p><WhatsAppLink message={`Hello Pristine Caviar, I would like assistance with the ${name} route.`}>Discuss your requirement</WhatsAppLink></article>)}</div></div></section></>; }

export function SturgeonAndConsultancySections() { const products=[["Fresh Sturgeon Fillet","Pristine, delicate flavour with a firm, but tender texture.","fresh"],["Frozen Sturgeon Fillet","Premium cut, preserved at peak freshness for exceptional quality.","frozen"],["Smoked Sturgeon Fillet","Rich, aromatic and naturally smoked for a distinctive depth of flavour.","smoked"],["Whole Sturgeon","For large-scale culinary, research and aquaculture requirements.","whole"]] as const; return <><section className="content-section sturgeon-section" id="sturgeon"><div className="sturgeon-shell"><header className="sturgeon-header"><div><p className="sturgeon-eyebrow">Beyond caviar</p><h2>UAE-farmed sturgeon<span>.</span></h2></div><div className="sturgeon-intro"><p>Four rare sturgeon species, raised in the UAE&apos;s pristine waters, each with a distinct flavour, texture and character.</p><a href="#enquire" className="sturgeon-explore"><i />Explore species <b>&#8594;</b></a></div></header><div className="sturgeon-product-grid">{products.map(([name,description,image])=><article className={`sturgeon-product sturgeon-product-${image}`} key={name}><div className="sturgeon-product-image" role="img" aria-label={name}/><div className="sturgeon-product-copy"><h3>{name}</h3><p>{description}</p><a href="#enquire" className="sturgeon-product-cta">Discover {name.replace(" Fillet","")}<b>&#8594;</b></a></div></article>)}</div></div></section><section className="capabilities" id="consultancy"><div className="container"><p className="eyebrow">Aquaculture Consultancy</p><div className="section-title"><h2>From concept to<br />optimized production.</h2><p>Pristine provides end-to-end aquaculture consultancy for projects and operational requirements.</p></div><div className="cap-grid consultancy-grid">{consultancy.map(([title, text, Icon]) => <article key={title}><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div><WhatsAppLink className="button dark-content-button" message="Hello Pristine Caviar, I would like to discuss an aquaculture consultancy requirement.">Discuss a consultancy requirement</WhatsAppLink></div></section></>; }

export function OrderingAndQualitySections() { return <><section className="content-section ordering-section"><div className="container"><p className="eyebrow">Simple ordering</p><div className="content-heading"><h2>No prices.<br />No confusion.</h2><p>The website is a premium digital catalogue and enquiry engine. Tell us what you need and Pristine will respond with the appropriate availability and commercial offer.</p></div><div className="ordering-grid">{[["1", "Choose", "Select caviar or sturgeon and explore the relevant product information."], ["2", "Tell us the requirement", "Choose your customer type, product, format and approximate quantity."], ["3", "Continue on WhatsApp", "A structured message opens in WhatsApp so the sales conversation starts with useful context."]].map(([number, title, body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section><section className="quality-section" id="quality"><div className="container"><p className="eyebrow">Quality & Certifications</p><div className="content-heading"><h2>Standards customers<br />can see and trust.</h2><p>Certification and registration claims below are shown from the approved reference source and require client verification before final publication.</p></div><div className="certification-grid">{certifications.map(([title, body]) => <article key={title}><Check size={17} /><strong>{title}</strong><span>{body}</span></article>)}</div></div></section></>; }

export function EnquirySection() { const [sent, setSent] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const product = String(data.get("product")); const message = [`Hello Pristine Caviar, I would like to make an enquiry.`, `Customer type: ${data.get("customerType")}`, `Product: ${product}`, `Preferred format: ${data.get("format")}`, `Approx. quantity: ${data.get("quantity")}`, `Name / Company: ${data.get("name")}`, `Market / Emirate: ${data.get("market")}`, `Message: ${data.get("message")}`].join("\n"); window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); setSent(true); }; return <section className="enquiry-section" id="enquire"><div className="container enquiry-shell"><div><p className="eyebrow">Direct enquiry</p><h2>Tell us what<br />you&apos;re looking for.</h2><p>No checkout or published price is shown. Your enquiry continues directly with Pristine Caviar on WhatsApp.</p><a href="https://www.youtube.com/watch?v=1qG0osLDr0A" target="_blank" rel="noreferrer">Watch Pristine&apos;s story ↗</a><br /><a href="https://www.youtube.com/watch?v=CUBzeGdRuHU" target="_blank" rel="noreferrer">Watch the fish farm film ↗</a></div><form onSubmit={submit}><label>Customer type<select name="customerType" required><option>Trade / Distributor</option><option>Hotel / Restaurant / Catering</option><option>Retail / Supermarket</option><option>Private Customer</option><option>Aquaculture Consultancy / Project</option></select></label><label>Product<select name="product" required>{[...varieties.map(([name]) => name), ...sturgeon.map(([name]) => name), "Aquaculture Consultancy / Project"].map(option => <option key={option}>{option}</option>)}</select></label><label>Preferred format<select name="format"><option>Not sure / Please advise</option><option>30g</option><option>50g</option><option>100g</option><option>200g</option><option>500g</option><option>1kg</option><option>Bulk / Trade format</option><option>Consultancy / Project Scope</option></select></label><label>Approx. quantity<input name="quantity" /></label><label>Name / Company<input name="name" required /></label><label>Market / Emirate<input name="market" /></label><label className="full-field">Message<textarea name="message" rows={3} /></label><button className="button" type="submit">Continue on WhatsApp <ArrowUpRight size={14} /></button>{sent && <small>WhatsApp has been opened with your enquiry details.</small>}</form></div></section>; }
