"use client";

import { AnimatePresence, motion } from "motion/react";
import { ArrowUpRight, ChevronDown, ChevronUp, Menu, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";

type MenuKey = "company" | "collection" | "aquaculture" | "discover";
type MenuItem = { label: string; href: string; description?: string };

const menus: Record<MenuKey, { label: string; items: MenuItem[]; feature: { eyebrow: string; title: string; copy: string; href: string; image: string } }> = {
  company: { label: "Company", items: [{ label: "About Pristine", href: "/about", description: "Our purpose and point of view." }, { label: "Our Direction", href: "/about#direction", description: "A measured approach to premium aquaculture." }, { label: "Our Farm", href: "/farm", description: "Controlled farming in Abu Dhabi." }, { label: "Leadership", href: "/about#leadership", description: "The people behind Pristine." }, { label: "Quality", href: "/quality", description: "Standards from farm to tin." }], feature: { eyebrow: "About Pristine", title: "From Abu Dhabi, with control from farm to tin.", copy: "Pristine brings considered aquaculture, traceability and caviar selection together in one operation.", href: "/about", image: "/images/farm-intro.jpg" } },
  collection: { label: "Collection", items: [{ label: "Caviar Collection", href: "/caviar", description: "UAE-produced caviar selections." }, { label: "Explore Caviar", href: "/caviar#collection", description: "Find a selection for your table or business." }, { label: "Sturgeon", href: "/sturgeon", description: "Sturgeon supply and consultation." }, { label: "Selection Guidance", href: "/sturgeon#selection", description: "A direct route to the right format." }, { label: "Make an Enquiry", href: "/contact", description: "Speak with the Pristine team." }], feature: { eyebrow: "The Pristine Collection", title: "Caviar, selected with clarity.", copy: "Five distinct expressions, each selected for character, texture and occasion.", href: "/caviar", image: "/images/caviar-editorial.webp" } },
  aquaculture: { label: "Aquaculture", items: [{ label: "Aquaculture Consultancy", href: "/aquaculture", description: "Support from concept to operation." }, { label: "Feasibility Studies", href: "/aquaculture#feasibility", description: "Evaluate a project's practical direction." }, { label: "Farm Planning", href: "/aquaculture#planning", description: "Plan for the intended production model." }, { label: "RAS Design", href: "/aquaculture#ras", description: "Recirculating aquaculture systems." }, { label: "Operational Management", href: "/aquaculture#operations", description: "Disciplined daily operations." }, { label: "Biosecurity", href: "/aquaculture#biosecurity", description: "Protect stock health and continuity." }, { label: "Production Optimization", href: "/aquaculture#optimization", description: "Improve consistency and performance." }], feature: { eyebrow: "Aquaculture Consultancy", title: "From concept to optimized production.", copy: "Practical aquaculture expertise for projects that value control, quality and long-term performance.", href: "/aquaculture", image: "/images/farm-infrastructure-systems.jpg" } },
  discover: { label: "Discover", items: [{ label: "Sustainability", href: "/sustainability", description: "Responsibility through controlled production." }, { label: "How We Farm", href: "/farm#process", description: "The systems behind every selection." }, { label: "Our Story", href: "/farm#story", description: "An Abu Dhabi farming operation." }, { label: "Quality & Certifications", href: "/quality", description: "Standards customers can see and trust." }, { label: "FAQs", href: "/#faq", description: "Answers about Pristine caviar." }, { label: "Journal", href: "/journal", description: "Notes from Pristine." }], feature: { eyebrow: "The Pristine Farm", title: "A considered environment for exceptional caviar.", copy: "The details of water, care and traceability guide how we farm and how we select.", href: "/farm", image: "/images/farm-care-inspection.jpg" } },
};
const desktopLinks: ({ label: string; href: string } | { key: MenuKey })[] = [{ label: "Home", href: "/" }, { key: "company" }, { key: "collection" }, { key: "aquaculture" }, { key: "discover" }];
function sectionFor(pathname: string) { if (["/about", "/farm", "/quality"].includes(pathname)) return "company"; if (["/caviar", "/sturgeon"].includes(pathname)) return "collection"; if (pathname === "/aquaculture") return "aquaculture"; if (["/sustainability", "/journal"].includes(pathname)) return "discover"; return undefined; }

export function SiteHeader() {
  const [mobileOpen, setMobileOpen] = useState(false); const [mobileGroup, setMobileGroup] = useState<MenuKey | null>(null); const [activeMenu, setActiveMenu] = useState<MenuKey | null>(null); const [pathname, setPathname] = useState("");
  const headerRef = useRef<HTMLElement>(null); const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const cancelClose = () => { if (closeTimer.current) window.clearTimeout(closeTimer.current); }; const scheduleClose = () => { cancelClose(); closeTimer.current = window.setTimeout(() => setActiveMenu(null), 180); }; const closeAll = () => { cancelClose(); setActiveMenu(null); setMobileOpen(false); };
  useEffect(() => { setPathname(window.location.pathname); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") closeAll(); }; const onPointerDown = (event: MouseEvent) => { if (headerRef.current && !headerRef.current.contains(event.target as Node)) setActiveMenu(null); }; window.addEventListener("keydown", onKeyDown); document.addEventListener("mousedown", onPointerDown); return () => { window.removeEventListener("keydown", onKeyDown); document.removeEventListener("mousedown", onPointerDown); }; }, []);
  useEffect(() => { document.body.style.overflow = mobileOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [mobileOpen]); useEffect(() => () => cancelClose(), []);
  const activeSection = sectionFor(pathname);
  return <header ref={headerRef} className={`nav-wrap${mobileOpen ? " nav-is-open" : ""}`} onMouseLeave={scheduleClose}><div className="nav"><div className="nav-main"><a className="brand" href="/" aria-label="Pristine Fish Farm home"><img src="/images/pristine-fish-farm-logo.png" alt="Pristine Fish Farm" /></a><nav aria-label="Primary navigation" onMouseEnter={cancelClose}>{desktopLinks.map((item) => "key" in item ? <button key={item.key} type="button" className={`nav-trigger${activeMenu === item.key || activeSection === item.key ? " is-active" : ""}`} aria-expanded={activeMenu === item.key} aria-controls={`mega-${item.key}`} onMouseEnter={() => { cancelClose(); setActiveMenu(item.key); }} onFocus={() => { cancelClose(); setActiveMenu(item.key); }} onClick={() => setActiveMenu(activeMenu === item.key ? null : item.key)}>{menus[item.key].label}<ChevronDown size={15} /></button> : <a key={item.label} href={item.href} aria-current={pathname === item.href ? "page" : undefined} onMouseEnter={scheduleClose}>{item.label}</a>)}</nav></div><div className="nav-cta-shell"><a href="/contact" className="button">CONTACT <ArrowUpRight size={14} /></a></div><button className="mobile-menu-toggle" type="button" aria-label={mobileOpen ? "Close navigation" : "Open navigation"} aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X size={22} /> : <Menu size={22} />}</button></div>
    <AnimatePresence>{activeMenu && <motion.section id={`mega-${activeMenu}`} className="mega-menu" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .3, ease: "easeOut" }} onMouseEnter={cancelClose} aria-label={`${menus[activeMenu].label} menu`}><div className="mega-menu-links"><p>{menus[activeMenu].label}</p>{menus[activeMenu].items.map((item, index) => <motion.a key={item.href} href={item.href} onClick={closeAll} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .04 + index * .025, duration: .25 }}><span>{item.label}</span><small>{item.description}</small><ArrowUpRight size={15} /></motion.a>)}</div><a className="mega-menu-feature" href={menus[activeMenu].feature.href} onClick={closeAll}><div className="mega-feature-image"><img src={menus[activeMenu].feature.image} alt="" /></div><p>{menus[activeMenu].feature.eyebrow}</p><h2>{menus[activeMenu].feature.title}</h2><span>{menus[activeMenu].feature.copy}</span><strong>Discover more <ArrowUpRight size={15} /></strong></a></motion.section>}</AnimatePresence>
    <AnimatePresence>{mobileOpen && <motion.div className="mobile-menu" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .25 }} onClick={() => setMobileOpen(false)}><motion.div className="mobile-menu-content" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 18 }} transition={{ duration: .35, ease: "easeOut" }} onClick={event => event.stopPropagation()}><p>Explore Pristine</p><a className="mobile-menu-direct" href="/" onClick={closeAll}><span>Home</span><ArrowUpRight size={18} /></a>{(Object.keys(menus) as MenuKey[]).map((key) => <div className="mobile-menu-group" key={key}><button type="button" className="mobile-menu-group-trigger" aria-expanded={mobileGroup === key} onClick={() => setMobileGroup(mobileGroup === key ? null : key)}><span>{menus[key].label}</span>{mobileGroup === key ? <ChevronUp size={20} /> : <ChevronDown size={20} />}</button><AnimatePresence>{mobileGroup === key && <motion.div className="mobile-menu-submenu" initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: .25, ease: "easeOut" }}>{menus[key].items.map(item => <a href={item.href} key={item.href} onClick={closeAll}>{item.label}<ArrowUpRight size={15} /></a>)}</motion.div>}</AnimatePresence></div>)}<a className="mobile-menu-direct" href="/contact" onClick={closeAll}><span>Contact</span><ArrowUpRight size={18} /></a></motion.div></motion.div>}</AnimatePresence>
  </header>;
}
